[webserver]
port = ":4000"

# register data providers
[[providers]]
name = "unfaelle"           # provider name is referenced from map layers
type = "postgis"        # the type of data provider. currently only supports postgis
host = "postgis"      # postgis database host
port = 5432             # postgis database port
database = "ms_unfaelle"       # postgis database name
user = "postgres"         # postgis database user
password = "unfaelle_aua_aua"           # postgis database password
srid = 3857             # The default srid for this provider. If not provided it will be WebMercator (3857)

[[providers.layers]]
  name = "unfaelle"
  tablename = "unfalldaten_geometries"
  geometry_fieldname = "the_geom"
  id_fieldname = "id"
  srid = 4326

[[maps]]
name = "unfaelle"

  [[maps.layers]]
  provider_layer = "unfaelle.unfaelle"
  min_zoom = 10
  max_zoom = 22


