COPY (
  SELECT
    id,
    data->'source_file' AS source_file,
    data->'import_timestamp' AS import_timestamp,
    data->'source_file_hash' AS source_file_hash,
    data->'source_row_number' AS source_row_number,
    data->'place' AS place,
    data->'place_near'AS place_near,
    data->'day_of_week' AS day_of_week,
    data->'date' AS date,
    data->'time_of_day' AS time_of_day,
    data->'accident_category' AS accident_category,
    data->'hit_and_run' AS hit_and_run,
    data->'urban' AS urban,
    data->'extra_urban' AS extra_urban,
    data->'deaths' AS deaths,
    data->'seriously_injured' AS seriously_injured,
    data->'slightly_injured' AS slightly_injured,
    data->'number_of_participants' AS number_of_participants,
    data->'pedestrian' AS pedestrian,
    data->'bicycle' AS bicycle,
    data->'helmet' AS helmet,
    data->'small_moped' AS small_moped,
    data->'moped' AS moped,
    data->'motorcycle' AS motorcycle,
    data->'car' AS car,
    data->'lorry' AS lorry,
    data->'omnibus' AS omnibus,
    data->'other_road_user' AS other_road_user,
    data->'participants_01' AS participants_01,
    data->'participants_01_registration' AS participants_01_registration,
    data->'participants_02' AS participants_02,
    data->'participants_02_registration' AS participants_02_registration,
    data->'alcoholized' AS alcoholized,
    data->'accident_type' AS accident_type,
    data->'cause_1_4' AS cause_1_4,
    data->'cause_2' AS cause_2,
    data->'cause_3' AS cause_3,
    data->'cause_other' AS cause_other,
    data->'cause_02' AS cause_02,
    data->'light_conditions' AS light_conditions,
    data->'road_condition' AS road_condition,
    data->'participants_child' AS participants_child,
    data->'participants_18_24' AS participants_18_24,
    data->'participants_senior' AS participants_senior,
    data->'participants_age_01' AS participants_age_01,
    data->'participants_age_02' AS participants_age_02
  FROM objects
  WHERE
    resource_name = 'record' AND
    parent_id = '/buckets/accidents/collections/accidents_raw'
    ) TO STDOUT
  WITH DELIMITER ',' ENCODING 'utf8' NULL '';
