version: "2.1"

services:
  postgis:
    image: mdillon/postgis:9.5
    volumes:
      - ./api/data.sql.gz:/docker-entrypoint-initdb.d/0data.sql.gz
      - ./api/postgrest.sql:/docker-entrypoint-initdb.d/1postgrest.sql
    environment:
      - POSTGRES_PASSWORD=unfaelle_aua_aua
      - POSTGRES_DB=ms_unfaelle
    networks:
      - database
  postgrest:
    build:
      context: ./api
    environment:
      - PG_ENV_POSTGRES_USER=postgres
      - PG_ENV_POSTGRES_PASSWORD=unfaelle_aua_aua
      - PG_PORT_5432_TCP_ADDR=postgis
      - PG_PORT_5432_TCP_PORT=5432
      - PG_ENV_POSTGRES_DB=ms_unfaelle
      - POSTGREST_SCHEMA=postgrest_views
    ports:
      - "3000:3000"
    depends_on:
      - postgis
    networks:
      - database
  protobuf:
    build:
      context: ./protobuf-server
    volumes:
      - ./protobuf-server/config.toml:/config.toml
    ports:
      - "4000:4000"
    depends_on:
      - postgis
    networks:
      - database

# geocoders

  # caddy image for load balancing
  proxy:
    image: abiosoft/caddy:latest
    volumes:
      - ./locations/Caddyfile:/etc/Caddyfile
    networks:
      - geocoding
    depends_on:
      - overpass
      - nominatim
  overpass:
    build:
      context: locations/overpass-mediasuite
    networks:
      - geocoding
  nominatim:
    build:
      context: locations/nominatim-mediagis
    networks:
      - geocoding

  runner:
    image: node:7
    volumes:
      - ./locations/geocode_js:/geocode
    command: [node, /geocode/index.js]
    networks:
      - database
      - geocoding
    depends_on:
      - postgis
      - proxy

networks:
  database:
    driver: bridge
  geocoding:
    driver: bridge
