version: "2"

services:
  importer: &python
    build: ./processing
    volumes:
      - ./data:/data
      - ./processing:/processing
      - ./kinto:/kinto
    command: python processing/importer.py
    environment:
      KINTO_URL: http://kinto:8888/v1
      KINTO_ADMIN: admin
      KINTO_ADMIN_PASSWORD: banane
    depends_on:
      - kinto

  initializer:
    <<: *python
    restart: "no"
    command: bash /kinto/init.sh

  geocoder:
    <<: *python
    restart: "no"
    command: python processing/geocoder.py

  kinto:
    image: kinto/kinto-server:13.0.1
    ports:
      - 8888:8888
    volumes:
      - ./kinto/config:/etc/kinto
    depends_on:
      - postgres

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: accidents
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  nominatim-import:
    image: mediagis/nominatim:3.1
    volumes:
      - ./nominatim/muenster-regbez.osm.pbf:/data/muenster-regbez.osm.pbf
      - ./nominatim/postgres_data:/data/postgres_data
    command: sh /app/init.sh /data/muenster-regbez.osm.pbf postgres_data 4

  nominatim:
    image: mediagis/nominatim:3.1
    volumes:
      - ./nominatim/postgres_data:/var/lib/postgresql/9.5/main
    ports:
      - "8080:8080"
    command: bash /app/start.sh
