buckets:
  accidents:
    collections:
      accidents_raw:
        data:
          attachment:
            enabled: false
            required: false
          cache_expires: 0
          displayFields:
          - source_file
          - source_row_number
          - place
          - place_near
          id: accidents_raw
          last_modified: 1556457209943
          schema:
            properties:
              accident_category:
                type: integer
              accident_type:
                type: integer
              alcoholized:
                type: string
              bicycle:
                type: integer
              car:
                type: integer
              cause_02:
                type: string
              cause_1_4:
                type: integer
              cause_2:
                type: integer
              cause_3:
                type: integer
              cause_other:
                type: integer
              date:
                format: date
                pattern: ^([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))$
                type: string
              day_of_week:
                type: string
              deaths:
                type: integer
              extra_urban:
                type: string
              helmet:
                type: string
              hit_and_run:
                type: string
              import_timestamp:
                type: string
              light_conditions:
                type: string
              lorry:
                type: integer
              moped:
                type: integer
              motorcycle:
                type: integer
              number_of_participants:
                type: integer
              omnibus:
                type: integer
              other_road_user:
                type: integer
              participants_01:
                type: integer
              participants_01_registration:
                type: string
              participants_02:
                type: integer
              participants_02_registration:
                type: string
              participants_18_24:
                type: integer
              participants_age_01:
                type: integer
              participants_age_02:
                type: integer
              participants_child:
                type: string
              participants_senior:
                type: integer
              pedestrian:
                type: integer
              place:
                type: string
              place_near:
                type: string
              road_condition:
                type: string
              seriously_injured:
                type: integer
              slightly_injured:
                type: integer
              small_moped:
                type: integer
              source_file:
                type: string
              source_file_hash:
                type: string
              source_row_number:
                minimum: 1
                type: integer
              time_of_day:
                format: time
                pattern: ^(?:[01]\d|2[0123]):(?:[012345]\d):(?:[012345]\d)|^(?![\s\S])$
                type: string
              urban:
                type: string
            required:
            - source_file
            - import_timestamp
            - source_file_hash
            - source_row_number
            type: object
          sort: source_file
          uiSchema:
            accident_category:
              ui:readonly: true
            accident_type:
              ui:readonly: true
            alcoholized:
              ui:readonly: true
            bicycle:
              ui:readonly: true
            car:
              ui:readonly: true
            cause_02:
              ui:readonly: true
            cause_1_4:
              ui:readonly: true
            cause_2:
              ui:readonly: true
            cause_3:
              ui:readonly: true
            cause_other:
              ui:readonly: true
            date:
              ui:readonly: true
            day_of_week:
              ui:readonly: true
            deaths:
              ui:readonly: true
            extra_urban:
              ui:readonly: true
            helmet:
              ui:readonly: true
            hit_and_run:
              ui:readonly: true
            import_timestamp:
              ui:readonly: true
            light_conditions:
              ui:readonly: true
            lorry:
              ui:readonly: true
            moped:
              ui:readonly: true
            motorcycle:
              ui:readonly: true
            number_of_participants:
              ui:readonly: true
            omnibus:
              ui:readonly: true
            other_road_user:
              ui:readonly: true
            participants_01:
              ui:readonly: true
            participants_01_registration:
              ui:readonly: true
            participants_02:
              ui:readonly: true
            participants_02_registration:
              ui:readonly: true
            participants_18_24:
              ui:readonly: true
            participants_age_01:
              ui:readonly: true
            participants_age_02:
              ui:readonly: true
            participants_child:
              ui:readonly: true
            participants_senior:
              ui:readonly: true
            pedestrian:
              ui:readonly: true
            place:
              ui:readonly: true
            place_near:
              ui:readonly: true
            road_condition:
              ui:readonly: true
            seriously_injured:
              ui:readonly: true
            slightly_injured:
              ui:readonly: true
            small_moped:
              ui:readonly: true
            source_file:
              ui:readonly: true
            source_file_hash:
              ui:readonly: true
            source_row_number:
              ui:readonly: true
            time_of_day:
              ui:readonly: true
            ui:order:
            - source_file
            - source_row_number
            - place
            - place_near
            - day_of_week
            - date
            - time_of_day
            - accident_category
            - hit_and_run
            - urban
            - extra_urban
            - deaths
            - seriously_injured
            - slightly_injured
            - number_of_participants
            - pedestrian
            - bicycle
            - helmet
            - small_moped
            - moped
            - motorcycle
            - car
            - lorry
            - omnibus
            - other_road_user
            - participants_01
            - participants_01_registration
            - participants_02
            - participants_02_registration
            - alcoholized
            - accident_type
            - cause_1_4
            - cause_2
            - cause_3
            - cause_other
            - cause_02
            - light_conditions
            - road_condition
            - participants_child
            - participants_18_24
            - participants_senior
            - participants_age_01
            - participants_age_02
            - source_file_hash
            - import_timestamp
            urban:
              ui:readonly: true
        permissions:
          read:
          - account:admin
          - system.Authenticated
          - system.Everyone
          record:create:
          - account:admin
          write:
          - account:admin
      geometries:
        data:
          attachment:
            enabled: false
            required: false
          cache_expires: 0
          displayFields:
          - accident_id
          - used_geocoder
          - comment
          - lat
          - lon
          id: geometries
          last_modified: 1556457207702
          schema:
            properties:
              accident_id:
                type: string
              comment:
                type: string
              geocoded_timestamp:
                type: string
              lat:
                maximum: 52.5
                minimum: 51.5
                type: number
              lon:
                maximum: 7.9
                minimum: 7.2
                type: number
              used_geocoder:
                type: string
              used_query:
                type: string
            required:
            - lat
            - lon
            - geocoded_timestamp
            - accident_id
            type: object
          sort: -accident_id
          uiSchema:
            content:
              ui:widget: textarea
            ui:order:
            - accident_id
            - used_geocoder
            - comment
            - lat
            - lon
            - geocoded_timestamp
            - used_query
        permissions:
          read:
          - system.Authenticated
          - system.Everyone
          write:
          - account:admin
    data:
      id: accidents
      last_modified: 1556457381955
    groups: {}
    permissions:
      read:
      - system.Authenticated
      - system.Everyone
      write:
      - account:admin
